#!/bin/bash
# rsync using variables
 
IP=$(ifconfig|grep -E inet.*broad|awk '{ print $2; }')


#Find good port 
p=0;for port in $(seq 0 10);do echo "Check :$((6000+$p)) (:$p)";  nc -w0 127.0.0.1 $((6000+$p)) && DISPLAY="$IP:$p"; let p=p+1;  done;

xhost + $IP



docker run -it  -e DISPLAY=$IP:0 -v /tmp/.X11-unix:/tmp/.X11-unix  28b542bb8774